#!/usr/local/bin/bash

while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    -l|--log-file)
      logfile="$2"
      shift
      shift
      ;;
    -t|--work-time)
      worktime="$2"
      shift
      shift
      ;;
    -f|--entry-format)
      format="$2"
      shift
      shift
      ;;
  esac
done

logfile=${logfile:-$(mktemp pomod.$(date +%Y-%m-%d).XXXXXXXXX.log)}
worktime=${worktime:-1500}
format=${format:-"+%Y-%m-%dT%H:%M:%S"}

work() {
  echo -ne "!$(date "$format")\n" >> $logfile
  seq 1 $worktime | xargs -I{} sleep 1
  echo -ne ".$(date "$format")\n" >> $logfile
}

trap 'work' SIGHUP
while true; do sleep 1; done
